export enum ErrorMessageCode {
  UNAUTHORISED_USER = 'UNAUTHORISED_USER',

  USER_NOT_FOUND = 'USER_NOT_FOUND',

  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',

  INCORRET_PASSWORD = 'INCORRET_PASSWORD',
}
